### ISSUE TITLE
panic: concurrent map read and map write

### ISSUE THREAD

**Issue by LittleFox94** [DoodleScheduling/flux-build#52]
Hi,

in some cases, `flux-build` panics with a `fatal error: concurrent map read and map write`, see the output below.

`flux-build` was invoked with `flux-build ./clusters/kubermatic-seed/dev-0401/apps common > $someOutputFile` in this case, the kustomization at `common` only including some `HelmRepository` manifests, which are referenced by `HelmRelease`s in the other kustomization.

Retrying works most of the time and I do not yet have minimal example, if the stack trace isn't helping, I'll gladly try to find one.

<details>
<summary>Log including stack traces</summary>

```
2023-07-13T12:28:24.798Z	INFO	action/action.go:89	build kustomize path	{"path": "./clusters/kubermatic-seed/dev-0401/apps"}
2023-07-13T12:28:24.798Z	INFO	action/action.go:89	build kustomize path	{"path": "common"}
fatal error: concurrent map read and map write

goroutine 30 [running]:
sigs.k8s.io/kustomize/kyaml/openapi.isNamespaceScopedFromSchema(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/openapi.go:381
sigs.k8s.io/kustomize/kyaml/openapi.IsNamespaceScoped({{0xc001d2bf80, 0x18}, {0xc0031c48f0, 0xe}})
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/openapi.go:376 +0xa5
sigs.k8s.io/kustomize/kyaml/openapi.IsCertainlyClusterScoped(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/openapi.go:390
sigs.k8s.io/kustomize/kyaml/resid.NewGvk({0xc00317b290?, 0x2196ac3?}, {0xc00317b2a6?, 0xc000eca200?}, {0xc0031c48f0?, 0x14?})
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/resid/gvk.go:27 +0x131
sigs.k8s.io/kustomize/kyaml/resid.GvkFromNode(0x0?)
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/resid/gvk.go:33 +0xd3
sigs.k8s.io/kustomize/api/resource.(*Resource).GetGvk(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/resource/resource.go:57
sigs.k8s.io/kustomize/api/resource.(*Resource).CurId(0xc0031de320)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/resource/resource.go:442 +0x65
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).Append(0xc002ca0678, 0xc0031de320)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/resmap/reswrangler.go:77 +0x45
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).appendAll(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/resmap/reswrangler.go:468
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).AppendAll(0xc0031c4be0?, {0x2535710?, 0xc002ca0a50?})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/resmap/reswrangler.go:462 +0xaa
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).AppendAll(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/accumulator/resaccumulator.go:45
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).MergeAccumulator(0xc002bf4c40, 0xc002bf4d40)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/accumulator/resaccumulator.go:95 +0x53
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateDirectory(0xc0002dacd0, 0xc002bf4c40, {0x251b308?, 0xc0002dad70}, 0x0)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:515 +0x67c
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateResources(0xc0002dacd0, 0x7eff0ef455b8?, {0xc002cb3e00?, 0x2, 0xc002c656e0?})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:429 +0x2a5
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc0002dacd0, 0x0?)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:188 +0x3d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0xc002c9fe10?)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:181 +0x105
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateDirectory(0xc00060c050, 0xc000392200, {0x251b308?, 0xc0002dac80}, 0x0)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:509 +0x64f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateResources(0xc00060c050, 0x7eff0ef45f18?, {0xc0000b3560?, 0x9, 0xc000710d20?})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:429 +0x2a5
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc00060c050, 0x14fb27d?)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:188 +0x3d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0x0?)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:181 +0x105
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc00060c050)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:127 +0x5f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:118
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc000ecbd18, {0x2525b80, 0x36bdf40}, {0x7fffecdc88ba, 0x28})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/krusty/kustomizer.go:88 +0x317
github.com/doodlescheduling/flux-build/internal/build.(*Kustomize).buildKustomization(0x0?, {0x7fffecdc88ba, 0x28})
	/go/src/github.com/DoodleScheduling/flux-build/internal/build/kustomize.go:99 +0x5db
github.com/doodlescheduling/flux-build/internal/build.(*Kustomize).Build(0x4b506566696e6b77?, {0x201?, 0x7add000000000000?})
	/go/src/github.com/DoodleScheduling/flux-build/internal/build/kustomize.go:35 +0x25
github.com/doodlescheduling/flux-build/internal/action.(*Action).Run.func3({0x2519bd8?, 0xc000844550?})
	/go/src/github.com/DoodleScheduling/flux-build/internal/action/action.go:96 +0x9f
github.com/doodlescheduling/flux-build/internal/worker.(*pool).runTask.func1()
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:134 +0x6b
created by github.com/doodlescheduling/flux-build/internal/worker.(*pool).runTask
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:132 +0x8a

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000063b00?)
	/usr/local/go/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc000063980?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x4b
github.com/doodlescheduling/flux-build/internal/worker.(*pool).Wait(0xc000846d20)
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:142 +0x2f
github.com/doodlescheduling/flux-build/internal/action.(*Action).exit(0xc000927280, {0xc001c40d88?, 0x1, 0x21c1a4a?})
	/go/src/github.com/DoodleScheduling/flux-build/internal/action/action.go:167 +0x62
github.com/doodlescheduling/flux-build/internal/action.(*Action).Run(0xc000927280, {0x2519c10?, 0xc00005c108?})
	/go/src/github.com/DoodleScheduling/flux-build/internal/action/action.go:130 +0x56b
main.main()
	/go/src/github.com/DoodleScheduling/flux-build/main.go:105 +0x799

goroutine 11 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xc0000a03c0?)
	/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x1bf

goroutine 58 [select]:
github.com/doodlescheduling/flux-build/internal/action.(*Action).Run.func2({0x2519bd8, 0xc000844500})
	/go/src/github.com/DoodleScheduling/flux-build/internal/action/action.go:69 +0xdf
github.com/doodlescheduling/flux-build/internal/worker.(*pool).runTask.func1()
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:134 +0x6b
created by github.com/doodlescheduling/flux-build/internal/worker.(*pool).runTask
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:132 +0x8a

goroutine 22 [select]:
github.com/doodlescheduling/flux-build/internal/worker.(*pool).start.func1()
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:79 +0xa8
created by github.com/doodlescheduling/flux-build/internal/worker.(*pool).start
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:77 +0x5a

goroutine 23 [select]:
github.com/doodlescheduling/flux-build/internal/worker.(*pool).start.func2()
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:110 +0xd2
created by github.com/doodlescheduling/flux-build/internal/worker.(*pool).start
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:106 +0xaf

goroutine 57 [select]:
github.com/doodlescheduling/flux-build/internal/action.(*Action).Run.func4({0x2519bd8, 0xc0008445f0})
	/go/src/github.com/DoodleScheduling/flux-build/internal/action/action.go:111 +0xb5
github.com/doodlescheduling/flux-build/internal/worker.(*pool).runTask.func1()
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:134 +0x6b
created by github.com/doodlescheduling/flux-build/internal/worker.(*pool).runTask
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:132 +0x8a

goroutine 25 [select]:
github.com/doodlescheduling/flux-build/internal/worker.(*pool).start.func2()
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:110 +0xd2
created by github.com/doodlescheduling/flux-build/internal/worker.(*pool).start
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:106 +0xaf

goroutine 26 [select]:
github.com/doodlescheduling/flux-build/internal/worker.(*pool).start.func1()
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:79 +0xa8
created by github.com/doodlescheduling/flux-build/internal/worker.(*pool).start
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:77 +0x5a

goroutine 27 [select]:
github.com/doodlescheduling/flux-build/internal/worker.(*pool).start.func2()
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:110 +0xd2
created by github.com/doodlescheduling/flux-build/internal/worker.(*pool).start
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:106 +0xaf

goroutine 28 [select]:
github.com/doodlescheduling/flux-build/internal/worker.(*pool).start.func1()
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:79 +0xa8
created by github.com/doodlescheduling/flux-build/internal/worker.(*pool).start
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:77 +0x5a

goroutine 29 [select]:
github.com/doodlescheduling/flux-build/internal/worker.(*pool).start.func2()
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:110 +0xd2
created by github.com/doodlescheduling/flux-build/internal/worker.(*pool).start
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:106 +0xaf

goroutine 31 [runnable]:
compress/flate.(*huffmanDecoder).init(0xc00087b450, {0xc001b9e8e8, 0x17, 0x1f?})
	/usr/local/go/src/compress/flate/inflate.go:116 +0x50f
compress/flate.(*decompressor).readHuffman(0xc00087ac00)
	/usr/local/go/src/compress/flate/inflate.go:459 +0x42f
compress/flate.(*decompressor).nextBlock(0xc00087ac00)
	/usr/local/go/src/compress/flate/inflate.go:322 +0x10e
compress/flate.(*decompressor).Read(0xc00087ac00, {0xc00117f000, 0x200, 0xc000a181d8?})
	/usr/local/go/src/compress/flate/inflate.go:347 +0x7e
compress/gzip.(*Reader).Read(0xc002b0f080, {0xc00117f000, 0x200, 0x200})
	/usr/local/go/src/compress/gzip/gunzip.go:252 +0xbb
bytes.(*Buffer).ReadFrom(0xc000a0d9b0, {0x24f68c0, 0xc002b0f080})
	/usr/local/go/src/bytes/buffer.go:202 +0x98
io.copyBuffer({0x24f6820, 0xc000a0d9b0}, {0x24f68c0, 0xc002b0f080}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:413 +0x14b
io.Copy(...)
	/usr/local/go/src/io/io.go:386
sigs.k8s.io/kustomize/kyaml/openapi/kustomizationapi.bindataRead({0x353f120, 0x1e0, 0x1e0}, {0x21d7da2, 0x1d})
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/kustomizationapi/swagger.go:28 +0x176
sigs.k8s.io/kustomize/kyaml/openapi/kustomizationapi.kustomizationapiSwaggerJsonBytes(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/kustomizationapi/swagger.go:86
sigs.k8s.io/kustomize/kyaml/openapi/kustomizationapi.kustomizationapiSwaggerJson()
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/kustomizationapi/swagger.go:93 +0x4c
sigs.k8s.io/kustomize/kyaml/openapi/kustomizationapi.Asset({0x21d7da2, 0x1d})
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/kustomizationapi/swagger.go:109 +0x76
sigs.k8s.io/kustomize/kyaml/openapi/kustomizationapi.MustAsset({0x21d7da2, 0x1d})
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/kustomizationapi/swagger.go:121 +0x27
sigs.k8s.io/kustomize/kyaml/openapi.initSchema()
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/openapi.go:620 +0xa6
sigs.k8s.io/kustomize/kyaml/openapi.isNamespaceScopedFromSchema(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/openapi.go:380
sigs.k8s.io/kustomize/kyaml/openapi.IsNamespaceScoped({{0xc0007f6960, 0x20}, {0xc0006e0270, 0xe}})
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/openapi.go:376 +0x88
sigs.k8s.io/kustomize/kyaml/openapi.IsCertainlyClusterScoped(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/openapi/openapi.go:390
sigs.k8s.io/kustomize/kyaml/resid.NewGvk({0xc0002cc960?, 0x2196ac3?}, {0xc0002cc979?, 0xc0006e02c0?}, {0xc0006e0270?, 0x0?})
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/resid/gvk.go:27 +0x131
sigs.k8s.io/kustomize/kyaml/resid.GvkFromNode(0x40dc8a?)
	/go/pkg/mod/sigs.k8s.io/kustomize/kyaml@v0.13.9/resid/gvk.go:33 +0xd3
sigs.k8s.io/kustomize/api/resource.(*Resource).GetGvk(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/resource/resource.go:57
sigs.k8s.io/kustomize/api/resource.(*Resource).CurId(0xc000175b30)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/resource/resource.go:442 +0x65
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).Append(0xc0008518d8, 0xc000175b30)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/resmap/reswrangler.go:77 +0x45
sigs.k8s.io/kustomize/api/resmap.newResMapFromResourceSlice({0xc000873fc0, 0x1, 0xc000624af8?})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/resmap/factory.go:130 +0x8c
sigs.k8s.io/kustomize/api/resmap.(*Factory).NewResMapFromBytes(0xc0001758b0?, {0xc000015800?, 0x18?, 0x2155160?})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/resmap/factory.go:73 +0x45
sigs.k8s.io/kustomize/api/resmap.(*Factory).FromFile(0xc00014b530?, {0x251b308?, 0xc0001758b0?}, {0xc0007ad248, 0x18})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/resmap/factory.go:60 +0x5a
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateFile(0xc000175900, 0xc000406cc0, {0xc0007ad248, 0x18})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:525 +0x66
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateResources(0xc000175900, 0x7eff0ef455b8?, {0xc000847800?, 0x5, 0xc000537bc0?})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:408 +0x9e
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc000175900, 0x0?)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:188 +0x3d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0xc0006e01f0?)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:181 +0x105
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateDirectory(0xc000175810, 0xc000406b40, {0x251b308?, 0xc0001758b0}, 0x0)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:509 +0x64f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateResources(0xc000175810, 0x7eff0ef455b8?, {0xc0005a84c0?, 0x1, 0xc000537680?})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:429 +0x2a5
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc000175810, 0x14fb27d?)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:188 +0x3d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0x0?)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:181 +0x105
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc000175810)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:127 +0x5f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/internal/target/kusttarget.go:118
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc000a19d18, {0x2525b80, 0x36bdf40}, {0x7fffecdc88e3, 0x6})
	/go/pkg/mod/sigs.k8s.io/kustomize/api@v0.12.1/krusty/kustomizer.go:88 +0x317
github.com/doodlescheduling/flux-build/internal/build.(*Kustomize).buildKustomization(0x0?, {0x7fffecdc88e3, 0x6})
	/go/src/github.com/DoodleScheduling/flux-build/internal/build/kustomize.go:99 +0x5db
github.com/doodlescheduling/flux-build/internal/build.(*Kustomize).Build(0x2014b5067?, {0x0?, 0x189a940e42a00?})
	/go/src/github.com/DoodleScheduling/flux-build/internal/build/kustomize.go:35 +0x25
github.com/doodlescheduling/flux-build/internal/action.(*Action).Run.func3({0x2519bd8?, 0xc000844550?})
	/go/src/github.com/DoodleScheduling/flux-build/internal/action/action.go:96 +0x9f
github.com/doodlescheduling/flux-build/internal/worker.(*pool).runTask.func1()
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:134 +0x6b
created by github.com/doodlescheduling/flux-build/internal/worker.(*pool).runTask
	/go/src/github.com/DoodleScheduling/flux-build/internal/worker/pool.go:132 +0x8a

```
</details>

**Comment by raffis** [comment]
Thanks for reporting this.
This can occur if flux-build is executed with more than one path. The reason is explained in the fix: #53
